name: PR Comment

on:
 pull_request:
  brances: ['*']

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - env: 
          PR_NAMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$(curl ifconfig.co/json)
          export ip=$(echo $body | jq '.ip')
          export country=$(echo $body | jq '.country')
          gh pr comment $PR_NAMBER --body "This was run from Address: $ip located at $country" --repo $GITHUB_REPOSITORY